services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/init:/etc/localstack/init/ready.d